### ISSUE TITLE
Add clients from resseler

### ISSUE THREAD

**Issue by ronydj** [infobip/oneapi-dot-net#3]
Guys,
Is there any way to create an client, from an re-seller account, using the API ?

**Comment by solutionrepublic** [comment]
I am unable to send a SMS. It seems it connects well as I get no exception but return result is False when actually send a SMS:

-------------------------------------------------
import oneapi as oneapi
import oneapi.models as models

INFOBIP_USER_ID = 'myuserid'
INFOBIP_PWD = 'mypwd'

def sendSMS(toNumber, message):
    try:
        smsClient = oneapi.SmsClient(INFOBIP_USER_ID, INFOBIP_PWD )
    except Exception as excp:
        logging.error(str(excp))

    sms = models.SMSRequest()
    sms.sender_address = toNumber
    sms.address = toNumber
    sms.message = message
    sms.callback_data = 'Any string'
    try:
        result = smsClient.send_sms(sms)
    except Exception as excp:
        logging.error(str(excp))
    # store client correlator because we can later query for the delivery status with it:
    client_correlator = result.client_correlator
    query_status = smsClient.query_delivery_status(client_correlator)
    return query_status.delivery_info
    #delivery_status = query_status.delivery_info[0].delivery_status

**Comment by ib-mmilakovic** [comment]
Hi,

Can you tell us which oneapi library do you use so we could try to reproduce your use case? Is it [Python](https://github.com/infobip/oneapi-python), [Ruby](https://github.com/infobip/oneapi-ruby) or something else? 

Next time please post your issue on appropriate repository. 

Thank you,
Milos

**Comment by solutionrepublic** [comment]
Hi,
Ok sorry, i didn't realize i am posting it under DotNet. I am using Python library. Thanks

**Comment by ib-mmilakovic** [comment]
Hi,

I have tried to run your code and I was unable to send message also. Solution is to call *send_sms* method with three arguments (instead of one). These arguments are:

1. **SMSRequest** which you already send
2. **request header**
3. **data format**

See how it should be implemented:

```python
data_format = "url"
if args.data_format:
    if (args.data_format == "json"):
        data_format = "json"

header = None
if 'accept' in locals():
    if args.accept:
        header = {"accept" : args.accept}

try:
    sms_client = oneapi.SmsClient(args.username, args.password)
except Exception as excp:
    logging.error(str(excp))

sms = models.SMSRequest()
sms.sender_address = args.sender
sms.address = args.address
sms.message = 'Test message 3'
sms.callback_data = 'Any string'
sms.client_correlator = 'your_client_correlator'
result = sms_client.send_sms(sms, header, data_format)

# store client correlator because we can later query for the delivery status with it:
client_correlator = result.client_correlator

# Few seconds later we can check for the sending status
time.sleep(10)
query_status = sms_client.query_delivery_status(client_correlator, args.sender)
delivery_status = query_status.delivery_info[0].delivery_status
print(delivery_status)
```

If you have any other questions please contact our support (<mailto:support@infobip.com>) or post your question on github repository. 

Best regards,
Milos
